### ISSUE TITLE
Deprecated selector in `blueforest-syntax\index.less`

### ISSUE THREAD

**Issue by Abyss03** [alonsodomin/atom-blueforest-syntax-theme#1]
In `blueforest-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection,
:host .selection` => `atom-text-editor .selection,atom-text-editor .selection`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor[mini] .scroll-view,
:host([mini]) .scroll-view` => `atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view`

* `.comment` => `.syntax--comment`

* `.comment .markup.link` => `.syntax--comment .syntax--markup.syntax--link`

* `.keyword` => `.syntax--keyword`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword.operator.logical` => `.syntax--keyword.syntax--operator.syntax--logical`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.sy`

**Comment by Abyss03** [comment]
I love using this syntax, don't want support for it to drop if atom suddenly stops using automatic compatibility changes.

**Comment by alonsodomin** [comment]
Thanks for the work on reporting this, I'll try to address the changes as soon as possible.
